"""Generate LaTeX for book: only the CE-M PDG summary table (hand journal elsewhere)."""

from __future__ import annotations

import math
from datetime import datetime, timezone


def tex_decimal(x: float, decimals: int = 3) -> str:
    return f"{x:.{decimals}f}".replace(".", "{,}")


def tex_sci(x: float, sig: int = 2) -> str:
    if x == 0.0 or not math.isfinite(x):
        return "0"
    exp = int(math.floor(math.log10(abs(x))))
    mant = x / (10.0**exp)
    fmt = f"{{:.{sig}f}}".format(mant).replace(".", "{,}")
    return fmt + r"\times 10^{" + str(exp) + "}"


def _fragment_header() -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return "\n".join(
        [
            "% Auto-generated by scripts/gen_lab_records_tex.py — do not edit.",
            f"% Generated: {stamp}",
            "% Journal prose: book/sources/lab-journal/ (hand-authored).",
            "",
        ]
    )


def build_si_pdg_table_latex(*, device: str = "cpu") -> str:
    del device
    from mt_ca.si_constants import (
        M_ELECTRON_GEV_PDG,
        M_HIGGS_GEV_PDG,
        M_NEUTRON_GEV_PDG,
        M_PROTON_GEV_PDG,
        SI,
    )

    h = SI.higgs_mass_row()
    p = SI.proton_mass_row()
    e = SI.electron_mass_row()
    n = SI.neutron_mass_row()
    f = SI.force_ansatz_row()
    w = SI.weinberg_row()
    br = SI.alpha_si_bridge_row()

    def row(label: str, model: float, pdg: float, rel: float, check: str, dec: int = 4) -> str:
        return (
            f"{label} & {tex_decimal(model, dec)} & {tex_decimal(pdg, dec)} & "
            f"${tex_sci(rel)}$ & \\texttt{{{check}}} \\\\"
        )

    body = "\n".join(
        [
            row(r"$v$ [GeV]", float(h["v_GeV"]), 246.22, abs(float(h["v_GeV"]) - 246.22) / 246.22, "Higgs\\_mass", 2),
            row(r"$m_H$ [GeV]", float(h["m_H_GeV"]), M_HIGGS_GEV_PDG, float(h["m_H_rel_err"]), "Higgs\\_mass", 2),
            row(r"$m_p$ [GeV]", float(p["m_p_GeV"]), M_PROTON_GEV_PDG, float(p["m_p_rel_err"]), "Proton\\_mass", 4),
            row(r"$m_e$ [GeV]", float(e["m_e_GeV"]), M_ELECTRON_GEV_PDG, float(e["m_e_rel_err"]), "Electron\\_mass", 6),
            row(r"$m_n$ [GeV]", float(n["m_n_GeV"]), M_NEUTRON_GEV_PDG, float(n["m_n_rel_err"]), "Neutron\\_mass", 4),
            row(
                r"$\alpha^{-1}$",
                1.0 / float(br["alpha_preferred"]),
                137.035999177,
                abs(1.0 / float(br["alpha_preferred"]) - 137.035999177) / 137.035999177,
                "Alpha\\_si\\_bridge",
                6,
            ),
            row(
                r"$\sin^2\theta_W$ (bare)",
                float(w["sin2_theta_W_bare"]),
                float(w["sin2_theta_W_PDG_MSbar"]),
                abs(float(w["bare_rel_err_vs_PDG"])),
                "Alpha\\_bridges",
                5,
            ),
            row(
                r"$\alpha_s(M_Z)$",
                float(f["alpha_s_MZ_model"]),
                float(f["alpha_s_MZ_pdg"]),
                float(f["alpha_s_MZ_rel_err"]),
                "---",
                5,
            ),
        ]
    )
    return "\n".join(
        [
            r"\begin{table}[htbp]",
            r"\centering",
            r"\caption{Серия CE-M: модель (upstream §8.2) vs эталон PDG/CODATA. "
            r"Не натурный эксперимент --- воспроизводимый прогон реестра.}",
            r"\label{tab:si-pdg-ce-m}",
            r"\small",
            r"\begin{tabular}{@{}lrrrl@{}}",
            r"\toprule",
            r"Наблюдаемая & Модель & Эталон & $|\delta|$ & Verify \\",
            r"\midrule",
            body,
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
            "",
        ]
    )


def generate_all_lab_fragments(*, device: str = "cpu") -> dict[str, str]:
    hdr = _fragment_header()
    return {
        "generated/lab-si-pdg-table.tex": hdr + build_si_pdg_table_latex(device=device),
    }
