"""Generate LaTeX fragments for book lab journals from live probes."""

from __future__ import annotations

import math
from datetime import datetime, timezone

from mt_ca.annihilation_pdg_tau import run_annihilation_pdg_tau_strict
from mt_ca.annihilation_t_stats import annihilation_t_stats_probe
from mt_ca.si_constants import TAU_PARA_PS_PDG_S, TAU_PARA_PS_PDG_U_S

# Two-sided Student t_{n-1, 0.975} (common ensemble sizes)
_T975: dict[int, float] = {
    1: 12.706,
    2: 4.303,
    3: 3.182,
    4: 2.776,
    5: 2.571,
    6: 2.447,
    7: 2.365,
    8: 2.306,
    9: 2.262,
    10: 2.228,
    11: 2.201,
    12: 2.179,
    15: 2.131,
    20: 2.086,
    30: 2.042,
}


def student_t_975(df: int) -> float:
    if df in _T975:
        return _T975[df]
    if df <= 0:
        return float("nan")
    # Wilson-Hilferty rough fallback for book automation only
    return 1.96 + 2.4 / df


def tex_decimal(x: float, decimals: int = 3) -> str:
    return f"{x:.{decimals}f}".replace(".", "{,}")


def tex_sci(x: float, sig: int = 2) -> str:
    if x == 0.0 or not math.isfinite(x):
        return "0"
    exp = int(math.floor(math.log10(abs(x))))
    mant = x / (10.0**exp)
    fmt = f"{{:.{sig}f}}".format(mant).replace(".", "{,}")
    return fmt + r"\times 10^{" + str(exp) + "}"


def _tex_paragraph(s: str) -> str:
    return " ".join(s.split())


def build_ce_a02_analysis_latex(*, device: str = "cpu", ensemble: int = 12) -> str:
    row = annihilation_t_stats_probe(size=160, steps=64, ensemble=ensemble, device=device)
    n = int(row.get("ensemble_axes") or 0)
    df = max(n - 1, 1)
    t_crit = student_t_975(df)
    mean_e = float(row["mean_axis_pi_err_rad"] or 0.0)
    sem = float(row.get("axis_pi_err_sem_rad") or float("nan"))
    std = float(row.get("axis_pi_err_std_rad") or float("nan"))
    half = t_crit * sem if sem == sem else float("nan")
    sp = r"\,"
    return _tex_paragraph(
        f"Тип~A (прогон реестра, $n={n}$): "
        rf"$\bar{{\varepsilon}}_{{\pi}}={tex_sci(mean_e)}{sp}\mathrm{{rad}}$; "
        rf"$s={tex_sci(std)}{sp}\mathrm{{rad}}$, "
        rf"$\mathrm{{SE}}=s/\sqrt{{n}}={tex_sci(sem)}{sp}\mathrm{{rad}}$; "
        rf"$t_{{{df},0.975}}={tex_decimal(t_crit, 3)}$, "
        rf"полуинтервал $t{sp}\mathrm{{SE}}\approx {tex_sci(half)}{sp}\mathrm{{rad}}$ "
        r"(\cref{sec:student}). Статистика прокси, не PDG. PDG $\tau$ --- CE-A-03."
    )


def build_ce_a03_analysis_latex(*, device: str = "cpu") -> str:
    row = run_annihilation_pdg_tau_strict(device=device)
    tau_pdg_ps = float(row["tau_para_PDG_s"]) * 1e12
    u_tau_ps = TAU_PARA_PS_PDG_U_S * 1e12
    tau_up_ps = float(row["tau_qed_upstream_s"]) * 1e12
    tau_cod_ps = float(row["tau_qed_CODATA_m_e_s"]) * 1e12
    rel_up = float(row["tau_rel_err_upstream"])
    rel_cod = float(row["tau_rel_err_CODATA_m_e"])
    u_mod_up = float(row["u_tau_mod_upstream_rel"])
    u_pdg = float(row["u_tau_PDG_rel"])
    en_up = float(row["E_n_upstream"])
    en_cod = float(row["E_n_CODATA_m_e_path"])
    ratio_q = float(row["ortho_para_ratio_qed_leading"])
    ratio_p = float(row["ortho_para_ratio_PDG"])
    ratio_rel = float(row["ortho_para_ratio_rel_err"])
    u_comb = math.sqrt(u_mod_up**2 + u_pdg**2)
    sp = r"\,"
    approx = r"\approx"
    return _tex_paragraph(
        rf"\textbf{{Эталон:}} $\tau_{{\mathrm{{PDG}}}}={tex_decimal(tau_pdg_ps, 3)}{sp}\mathrm{{ps}}$, "
        rf"$u(\tau){approx} {tex_decimal(u_tau_ps, 3)}{sp}\mathrm{{ps}}$ "
        rf"($u/\tau{approx} {tex_sci(u_pdg)}$). "
        rf"\textbf{{Косвенные модели}} (\eqref{{eq:para-ps-tau}}): "
        rf"$\tau_{{\mathrm{{up}}}}{approx} {tex_decimal(tau_up_ps, 2)}{sp}\mathrm{{ps}}$ "
        rf"($\delta/\tau{approx} {tex_sci(rel_up)}$); "
        rf"$\tau_{{\mathrm{{CODATA}}}}{sp}m_e{approx} {tex_decimal(tau_cod_ps, 2)}{sp}\mathrm{{ps}}$ "
        rf"($\delta/\tau{approx} {tex_sci(rel_cod)}$). "
        rf"\textbf{{GUM}} (\eqref{{eq:tau-relative-unc}}): "
        rf"$u_{{\mathrm{{mod}}}}/\tau{approx} {tex_sci(u_mod_up)}$; "
        rf"$u_{{\mathrm{{comb}}}}/\tau{approx} {tex_sci(u_comb)}$; "
        rf"$E_n^{{(\mathrm{{up}})}}{approx} {tex_decimal(en_up, 2)}$ (\eqref{{eq:en-score}}). "
        rf"\textbf{{CODATA-path:}} $E_n{approx} {tex_decimal(en_cod, 1)}$ --- систематика типа~B (leading $\Gamma$), "
        r"не круговой вход. "
        rf"\textbf{{Ortho/para:}} leading ${approx} {tex_decimal(ratio_q, 0)}$ vs PDG ${approx} {tex_decimal(ratio_p, 0)}$ "
        rf"($\delta_{{\mathrm{{rel}}}}{approx} {tex_decimal(ratio_rel * 100, 1)}\%$). "
        r"Источник: \texttt{Annihilation\_PDG\_tau\_strict}."
    )


def _fragment_header() -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return "\n".join(
        [
            "% Auto-generated by scripts/gen_lab_records_tex.py — do not edit.",
            f"% Generated: {stamp}",
            "",
        ]
    )


def generate_floors_lab_fragments(*, device: str = "cpu") -> dict[str, str]:
    """Map relative path under book/sources/ → fragment body (no preamble)."""
    ce_a02 = build_ce_a02_analysis_latex(device=device)
    ce_a03 = build_ce_a03_analysis_latex(device=device)
    hdr = _fragment_header()
    return {
        "generated/lab-ce-a-02-analysis.tex": hdr + ce_a02 + "\n",
        "generated/lab-ce-a-03-analysis.tex": hdr + ce_a03 + "\n",
    }
