"""Generate LaTeX fragments for book lab journals from live probes."""

from __future__ import annotations

import math
from datetime import datetime, timezone

from mt_ca.annihilation_pdg_tau import run_annihilation_pdg_tau_strict
from mt_ca.annihilation_t_stats import annihilation_t_stats_probe
from mt_ca.si_constants import TAU_PARA_PS_PDG_S, TAU_PARA_PS_PDG_U_S

# Two-sided Student t_{n-1, 0.975} (common ensemble sizes)
_T975: dict[int, float] = {
    1: 12.706,
    2: 4.303,
    3: 3.182,
    4: 2.776,
    5: 2.571,
    6: 2.447,
    7: 2.365,
    8: 2.306,
    9: 2.262,
    10: 2.228,
    11: 2.201,
    12: 2.179,
    15: 2.131,
    20: 2.086,
    30: 2.042,
}


def student_t_975(df: int) -> float:
    if df in _T975:
        return _T975[df]
    if df <= 0:
        return float("nan")
    # Wilson-Hilferty rough fallback for book automation only
    return 1.96 + 2.4 / df


def tex_decimal(x: float, decimals: int = 3) -> str:
    return f"{x:.{decimals}f}".replace(".", "{,}")


def tex_sci(x: float, sig: int = 2) -> str:
    if x == 0.0 or not math.isfinite(x):
        return "0"
    exp = int(math.floor(math.log10(abs(x))))
    mant = x / (10.0**exp)
    fmt = f"{{:.{sig}f}}".format(mant).replace(".", "{,}")
    return fmt + r"\times 10^{" + str(exp) + "}"


def _tex_paragraph(s: str) -> str:
    return " ".join(s.split())


def build_ce_a02_analysis_latex(*, device: str = "cpu", ensemble: int = 12) -> str:
    row = annihilation_t_stats_probe(size=160, steps=64, ensemble=ensemble, device=device)
    n = int(row.get("ensemble_axes") or 0)
    df = max(n - 1, 1)
    t_crit = student_t_975(df)
    mean_e = float(row["mean_axis_pi_err_rad"] or 0.0)
    sem = float(row.get("axis_pi_err_sem_rad") or float("nan"))
    std = float(row.get("axis_pi_err_std_rad") or float("nan"))
    half = t_crit * sem if sem == sem else float("nan")
    sp = r"\,"
    return _tex_paragraph(
        f"Тип~A (прогон реестра, $n={n}$): "
        rf"$\bar{{\varepsilon}}_{{\pi}}={tex_sci(mean_e)}{sp}\mathrm{{rad}}$; "
        rf"$s={tex_sci(std)}{sp}\mathrm{{rad}}$, "
        rf"$\mathrm{{SE}}=s/\sqrt{{n}}={tex_sci(sem)}{sp}\mathrm{{rad}}$; "
        rf"$t_{{{df},0.975}}={tex_decimal(t_crit, 3)}$, "
        rf"полуинтервал $t{sp}\mathrm{{SE}}\approx {tex_sci(half)}{sp}\mathrm{{rad}}$ "
        r"(\cref{sec:student}). Статистика прокси, не PDG. PDG $\tau$ --- CE-A-03."
    )


def build_ce_a03_analysis_latex(*, device: str = "cpu") -> str:
    row = run_annihilation_pdg_tau_strict(device=device)
    tau_pdg_ps = float(row["tau_para_PDG_s"]) * 1e12
    u_tau_ps = TAU_PARA_PS_PDG_U_S * 1e12
    tau_up_ps = float(row["tau_qed_upstream_s"]) * 1e12
    tau_cod_ps = float(row["tau_qed_CODATA_m_e_s"]) * 1e12
    rel_up = float(row["tau_rel_err_upstream"])
    rel_cod = float(row["tau_rel_err_CODATA_m_e"])
    u_mod_up = float(row["u_tau_mod_upstream_rel"])
    u_pdg = float(row["u_tau_PDG_rel"])
    en_up = float(row["E_n_upstream"])
    en_cod = float(row["E_n_CODATA_m_e_path"])
    ratio_q = float(row["ortho_para_ratio_qed_leading"])
    ratio_p = float(row["ortho_para_ratio_PDG"])
    ratio_rel = float(row["ortho_para_ratio_rel_err"])
    u_comb = math.sqrt(u_mod_up**2 + u_pdg**2)
    sp = r"\,"
    approx = r"\approx"
    return _tex_paragraph(
        rf"\textbf{{Эталон:}} $\tau_{{\mathrm{{PDG}}}}={tex_decimal(tau_pdg_ps, 3)}{sp}\mathrm{{ps}}$, "
        rf"$u(\tau){approx} {tex_decimal(u_tau_ps, 3)}{sp}\mathrm{{ps}}$ "
        rf"($u/\tau{approx} {tex_sci(u_pdg)}$). "
        rf"\textbf{{Косвенные модели}} (\eqref{{eq:para-ps-tau}}): "
        rf"$\tau_{{\mathrm{{up}}}}{approx} {tex_decimal(tau_up_ps, 2)}{sp}\mathrm{{ps}}$ "
        rf"($\delta/\tau{approx} {tex_sci(rel_up)}$); "
        rf"$\tau_{{\mathrm{{CODATA}}}}{sp}m_e{approx} {tex_decimal(tau_cod_ps, 2)}{sp}\mathrm{{ps}}$ "
        rf"($\delta/\tau{approx} {tex_sci(rel_cod)}$). "
        rf"\textbf{{GUM}} (\eqref{{eq:tau-relative-unc}}): "
        rf"$u_{{\mathrm{{mod}}}}/\tau{approx} {tex_sci(u_mod_up)}$; "
        rf"$u_{{\mathrm{{comb}}}}/\tau{approx} {tex_sci(u_comb)}$; "
        rf"$E_n^{{(\mathrm{{up}})}}{approx} {tex_decimal(en_up, 2)}$ (\eqref{{eq:en-score}}). "
        rf"\textbf{{CODATA-path:}} $E_n{approx} {tex_decimal(en_cod, 1)}$ --- систематика типа~B (leading $\Gamma$), "
        r"не круговой вход. "
        rf"\textbf{{Ortho/para:}} leading ${approx} {tex_decimal(ratio_q, 0)}$ vs PDG ${approx} {tex_decimal(ratio_p, 0)}$ "
        rf"($\delta_{{\mathrm{{rel}}}}{approx} {tex_decimal(ratio_rel * 100, 1)}\%$). "
        r"Источник: \texttt{Annihilation\_PDG\_tau\_strict}."
    )


def _fragment_header() -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return "\n".join(
        [
            "% Auto-generated by scripts/gen_lab_records_tex.py — do not edit.",
            f"% Generated: {stamp}",
            "",
        ]
    )


def build_ce_m00_analysis_latex(*, device: str = "cpu") -> str:
    del device
    from mt_ca.si_constants import SI

    row = SI.kappa_bottom_up_row()
    kappa = float(row["kappa_geom_FCC"])
    c0_over_c = float(row["c0_over_c"])
    ht_over_tp = float(row["hT_over_t_P"])
    inv_kappa = 1.0 / kappa
    approx = r"\approx"
    return _tex_paragraph(
        rf"Геометрия: $\kappa={tex_decimal(kappa, 6)}$ (вписанная сфера 1-tick; "
        rf"\texttt{{kappa\_not\_defined\_as\_c\_over\_c0}}). "
        rf"Планковский мост: $hT/t_P={tex_decimal(ht_over_tp, 6)}$; "
        rf"$c_0/c={tex_decimal(c0_over_c, 4)}{approx}{tex_decimal(inv_kappa, 4)}$ "
        rf"(не CODATA-$c$ на звене $\ell_P$). "
        rf"$E_0/E_P={tex_decimal(float(row['E_0_over_E_P']), 6)}$. "
        r"Проверка: \texttt{Kappa\_bottom\_up} (suite \texttt{carrier})."
    )


def build_ce_m01_analysis_latex(*, device: str = "cpu") -> str:
    from mt_ca.t.hydro_limit import classical_limit_sweep_row

    row = classical_limit_sweep_row(device=device, size=128)
    phi = row["phi_bz"]
    mad = row["madelung_long_wave"][-1]
    omega = float(mad.get("omega_tick") or float("nan"))
    lap = float(row["fcc_lap_coeff_at_k"])
    approx = r"\approx"
    omega_s = tex_decimal(omega, 4) if math.isfinite(omega) else r"\mathrm{?}"
    return _tex_paragraph(
        rf"Прокси IR на карте ($\Phi=\mathcal{{B}}z$): binomial$\to$Gaussian "
        rf"(\texttt{{coarse\_to\_gaussian}}={str(row['coarse_to_gaussian']).lower()}); "
        rf"FCC $\hat K\to 1-(2/3)k^2$ (коэфф. ${approx}{tex_decimal(lap, 4)}$ при $k=0.08$). "
        rf"Длинноволновый Madelung/Bohm $\to$ классика; фазовая скорость одного тика "
        rf"$\omega{approx}{omega_s}$ (natural, цель $\approx 1$ для macro-$c$). "
        rf"Readout $\Phi$: \texttt{{phi\_readout\_ok}}={str(phi.get('phi_readout_ok', False)).lower()}. "
        r"Проверки: \texttt{T\_classical\_limit}, \texttt{T\_hydro\_limit\_bundle} (suite \texttt{t\_macro})."
    )


def build_ce_m02_analysis_latex(*, device: str = "cpu") -> str:
    del device
    from mt_ca.si_constants import SI

    br = SI.alpha_si_bridge_row()
    up = SI.alpha_upstairs_mass_probe_row()
    a_inv = 1.0 / float(br["alpha_preferred"])
    approx = r"\approx"
    return _tex_paragraph(
        rf"Алгебра SI-моста: $\alpha^{{-1}}_{{\mathrm{{pref}}}}{approx}{tex_decimal(a_inv, 6)}$ "
        rf"(M={int(br['M'])}, $d={int(br['d'])}$, без $u(\alpha)$); "
        rf"контраст T-door $\approx {tex_decimal(float(br['T_lab_contrast_ppm']), 2)}\,$ppm. "
        rf"Каскад масс: $v{approx}{tex_decimal(float(up['v_GeV']), 2)}\,$GeV, "
        rf"$\delta m_H/m_H{approx}{tex_sci(float(up['m_H_rel_err']))}$, "
        rf"$\delta m_p{approx}{tex_sci(float(up['m_p_rel_err']))}$, "
        rf"$\delta m_e{approx}{tex_sci(float(up['m_e_rel_err']))}$ vs PDG (upstream §8.2). "
        r"Критерии: \texttt{Alpha\_si\_bridge}, \texttt{Alpha\_upstairs\_mass\_probe}."
    )


def build_ce_m03_analysis_latex(*, device: str = "cpu") -> str:
    del device
    from mt_ca.si_constants import (
        M_ELECTRON_GEV_PDG,
        M_HIGGS_GEV_PDG,
        M_NEUTRON_GEV_PDG,
        M_PROTON_GEV_PDG,
        SI,
    )

    h = SI.higgs_mass_row()
    p = SI.proton_mass_row()
    e = SI.electron_mass_row()
    n = SI.neutron_mass_row()
    f = SI.force_ansatz_row()
    w = SI.weinberg_row()
    sin2_rel = abs(float(w["sin2_theta_W_bare"]) - float(w["sin2_theta_W_PDG_MSbar"])) / float(
        w["sin2_theta_W_PDG_MSbar"]
    )
    lines = [
        rf"$v={tex_decimal(float(h['v_GeV']), 2)}$ GeV (PDG ${tex_decimal(246.22, 2)}$); "
        rf"$m_H={tex_decimal(float(h['m_H_GeV']), 2)}$ GeV ($|\delta|\approx {tex_sci(float(h['m_H_rel_err']))}$); "
        rf"$m_p={tex_decimal(float(p['m_p_GeV']), 4)}$ GeV ($|\delta|\approx {tex_sci(float(p['m_p_rel_err']))}$); "
        rf"$m_e={tex_decimal(float(e['m_e_GeV']), 6)}$ GeV ($|\delta|\approx {tex_sci(float(e['m_e_rel_err']))}$); "
        rf"$m_n={tex_decimal(float(n['m_n_GeV']), 4)}$ GeV ($|\delta|\approx {tex_sci(float(n['m_n_rel_err']))}$). "
        rf"$\sin^2\theta_W^{{(bare)}}=3/13$ ($|\delta|$ к MSbar $\approx {tex_sci(sin2_rel)}$). "
        rf"$\alpha_s(M_Z)={tex_decimal(float(f['alpha_s_MZ_model']), 5)}$ ($|\delta|\approx {tex_sci(float(f['alpha_s_MZ_rel_err']))}$). "
        r"Проверки: \texttt{Higgs\_mass}, \texttt{Proton\_mass}, \texttt{Electron\_mass}, \texttt{Neutron\_mass}."
    ]
    return _tex_paragraph("".join(lines))


def build_si_pdg_table_latex(*, device: str = "cpu") -> str:
    del device
    from mt_ca.si_constants import (
        M_ELECTRON_GEV_PDG,
        M_HIGGS_GEV_PDG,
        M_NEUTRON_GEV_PDG,
        M_PROTON_GEV_PDG,
        SI,
    )

    h = SI.higgs_mass_row()
    p = SI.proton_mass_row()
    e = SI.electron_mass_row()
    n = SI.neutron_mass_row()
    f = SI.force_ansatz_row()
    w = SI.weinberg_row()
    br = SI.alpha_si_bridge_row()

    def row(label: str, model: float, pdg: float, rel: float, check: str, dec: int = 4) -> str:
        return (
            f"{label} & {tex_decimal(model, dec)} & {tex_decimal(pdg, dec)} & "
            f"${tex_sci(rel)}$ & \\texttt{{{check}}} \\\\"
        )

    body = "\n".join(
        [
            row(r"$v$ [GeV]", float(h["v_GeV"]), 246.22, abs(float(h["v_GeV"]) - 246.22) / 246.22, "Higgs\\_mass", 2),
            row(r"$m_H$ [GeV]", float(h["m_H_GeV"]), M_HIGGS_GEV_PDG, float(h["m_H_rel_err"]), "Higgs\\_mass", 2),
            row(r"$m_p$ [GeV]", float(p["m_p_GeV"]), M_PROTON_GEV_PDG, float(p["m_p_rel_err"]), "Proton\\_mass", 4),
            row(r"$m_e$ [GeV]", float(e["m_e_GeV"]), M_ELECTRON_GEV_PDG, float(e["m_e_rel_err"]), "Electron\\_mass", 6),
            row(r"$m_n$ [GeV]", float(n["m_n_GeV"]), M_NEUTRON_GEV_PDG, float(n["m_n_rel_err"]), "Neutron\\_mass", 4),
            row(
                r"$\alpha^{-1}$",
                1.0 / float(br["alpha_preferred"]),
                137.035999177,
                abs(1.0 / float(br["alpha_preferred"]) - 137.035999177) / 137.035999177,
                "Alpha\\_si\\_bridge",
                6,
            ),
            row(
                r"$\sin^2\theta_W$ (bare)",
                float(w["sin2_theta_W_bare"]),
                float(w["sin2_theta_W_PDG_MSbar"]),
                abs(float(w["bare_rel_err_vs_PDG"])),
                "Alpha\\_bridges",
                5,
            ),
            row(
                r"$\alpha_s(M_Z)$",
                float(f["alpha_s_MZ_model"]),
                float(f["alpha_s_MZ_pdg"]),
                float(f["alpha_s_MZ_rel_err"]),
                "---",
                5,
            ),
        ]
    )
    return "\n".join(
        [
            r"\begin{table}[htbp]",
            r"\centering",
            r"\caption{Серия CE-M: модель (upstream §8.2) vs эталон PDG/CODATA. "
            r"Не натурный эксперимент --- воспроизводимый прогон реестра.}",
            r"\label{tab:si-pdg-ce-m}",
            r"\small",
            r"\begin{tabular}{@{}lrrrl@{}}",
            r"\toprule",
            r"Наблюдаемая & Модель & Эталон & $|\delta|$ & Verify \\",
            r"\midrule",
            body,
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
            "",
        ]
    )


def generate_construction_lab_fragments(*, device: str = "cpu") -> dict[str, str]:
    hdr = _fragment_header()
    return {
        "generated/lab-si-pdg-table.tex": hdr + build_si_pdg_table_latex(device=device),
        "generated/lab-ce-m-00-analysis.tex": hdr + build_ce_m00_analysis_latex(device=device) + "\n",
        "generated/lab-ce-m-01-analysis.tex": hdr + build_ce_m01_analysis_latex(device=device) + "\n",
        "generated/lab-ce-m-02-analysis.tex": hdr + build_ce_m02_analysis_latex(device=device) + "\n",
        "generated/lab-ce-m-03-analysis.tex": hdr + build_ce_m03_analysis_latex(device=device) + "\n",
    }


def generate_floors_lab_fragments(*, device: str = "cpu") -> dict[str, str]:
    """Map relative path under book/sources/ → fragment body (no preamble)."""
    ce_a02 = build_ce_a02_analysis_latex(device=device)
    ce_a03 = build_ce_a03_analysis_latex(device=device)
    hdr = _fragment_header()
    return {
        "generated/lab-ce-a-02-analysis.tex": hdr + ce_a02 + "\n",
        "generated/lab-ce-a-03-analysis.tex": hdr + ce_a03 + "\n",
    }


def generate_all_lab_fragments(*, device: str = "cpu") -> dict[str, str]:
    out: dict[str, str] = {}
    out.update(generate_construction_lab_fragments(device=device))
    out.update(generate_floors_lab_fragments(device=device))
    return out
