"""Шаблон соседства на решётке — канон FCC (3+1), гекс только для явного среза 2+1."""

CANON_NEIGHBOR_TEMPLATE = "fcc"
SLICE_NEIGHBOR_TEMPLATE = "hex"

# Совместимость (старое имя в коде и JSON)
CANON_NEIGHBOR_SCHEME = CANON_NEIGHBOR_TEMPLATE
SLICE_NEIGHBOR_SCHEME = SLICE_NEIGHBOR_TEMPLATE
CANON_STENCIL = CANON_NEIGHBOR_TEMPLATE
SLICE_STENCIL = SLICE_NEIGHBOR_TEMPLATE
