#!/usr/bin/env python3
"""Extract chapter/section numbers from construction \\newlabel → \\VolRef{key}."""
from __future__ import annotations

import re
import sys
from pathlib import Path

NEWLABEL = re.compile(r"^\\newlabel\{([^}]+)\}\{\{([\d.]+)")


def main() -> int:
    aux_path = Path(sys.argv[1])
    out_path = Path(sys.argv[2])
    labels: dict[str, str] = {}
    for line in aux_path.read_text(encoding="utf-8").splitlines():
        if "@cref" in line:
            continue
        m = NEWLABEL.match(line)
        if m:
            labels[m.group(1)] = m.group(2)
    lines = [
        "% Auto-generated by scripts/gen_construction_vol_refs.py — do not edit.",
        "\\makeatletter",
    ]
    for key, num in sorted(labels.items()):
        lines.append(f"\\expandafter\\newcommand\\csname VolRef@{key}\\endcsname{{{num}}}")
    lines.append(
        "\\newcommand{\\VolRef}[1]{\\@ifundefined{VolRef@#1}{??}{\\csname VolRef@#1\\endcsname}}"
    )
    lines.append("\\makeatother")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path} ({len(labels)} labels)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
